function [EVENT_ID,RETURN_CODE] = CREATE_EVENT(EVENT_NAME)

global Event_Set;
global SYSTEM_NUMBER_OF_EVENTS;
global MAX_NUMBER_OF_EVENTS;
global RETURN_CODE_TYPE;
global OPERATING_MODE_TYPE;
global Current_Partition_STATUS;

if EVENT_NAME_EXIST(EVENT_NAME)==1
    RETURN_CODE = RETURN_CODE_TYPE.NO_ACTION;
    return;
end

if SYSTEM_NUMBER_OF_EVENTS == MAX_NUMBER_OF_EVENTS
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_CONFIG;
    return;
end

if Current_Partition_STATUS.OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_MODE;
    return;
end

EVENT_ID = round( 1+(MAX_NUMBER_OF_EVENTS-1) *rand(1,1) );


Event_Set{1,numel(Event_Set)+1}= Event_TYPE(EVENT_ID,EVENT_NAME,0,[]);
   
SYSTEM_NUMBER_OF_EVENTS = SYSTEM_NUMBER_OF_EVENTS + 1;

RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR;










