global SAMPLING_PORT_ATTRIBUTE
SAMPLING_PORT_ATTRIBUTE.ID=0;
% SAMPLING_PORT_ATTRIBUTE.NAME;
% SAMPLING_PORT_ATTRIBUTE.REFRESH_PERIOD;
% SAMPLING_PORT_ATTRIBUTE.MAX_MESSAGE_SIZE;
% SAMPLING_PORT_ATTRIBUTE.PORT_DIRECTION;
SAMPLING_PORT_ATTRIBUTE.LAST_MSG_VALIDITY=16;