global SYSTEM_LIMIT_NUMBER_OF_PARTITIONS;
SYSTEM_LIMIT_NUMBER_OF_PARTITIONS = 32;

global SYSTEM_LIMIT_NUMBER_OF_MESSAGES;
SYSTEM_LIMIT_NUMBER_OF_MESSAGES = 512;

global SYSTEM_LIMIT_MESSAGE_SIZE;
SYSTEM_LIMIT_MESSAGE_SIZE = 8192;

global SYSTEM_LIMIT_NUMBER_OF_PROCESSES;
SYSTEM_LIMIT_NUMBER_OF_PROCESSES = 128;

global SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS;
SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS = 512;

global SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS;
SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS = 512;

global SYSTEM_LIMIT_NUMBER_OF_BUFFERS;
SYSTEM_LIMIT_NUMBER_OF_BUFFERS = 256;

global SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS;
SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS = 256;

global SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES;
SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES = 256;

global SYSTEM_LIMIT_NUMBER_OF_EVENTS;
SYSTEM_LIMIT_NUMBER_OF_EVENTS = 256;

global MAX_NAME_LENGTH;
MAX_NAME_LENGTH = 30;

global RETURN_CODE_TYPE;
RETURN_CODE_TYPE.NO_ERROR = 0;   
RETURN_CODE_TYPE.NO_ACTION = 1;  
RETURN_CODE_TYPE.NOT_AVAILABLE = 2;   
RETURN_CODE_TYPE.INVALID_PARAM = 3;  
RETURN_CODE_TYPE.INVALID_CONFIG = 4;  
RETURN_CODE_TYPE.INVALID_MODE = 5;  
RETURN_CODE_TYPE.TIMED_OUT = 6;       

global PORT_DIRECTION_TYPE;
PORT_DIRECTION_TYPE.SOURCE = 0;
PORT_DIRECTION_TYPE.DESTINATION = 1;

global QUEUING_DISCIPLINE_TYPE;
QUEUING_DISCIPLINE_TYPE.FIFO = 0;
QUEUING_DISCIPLINE_TYPE.PRIORITY = 1;

global INFINITE_TIME_VALUE;
INFINITE_TIME_VALUE = -1;

global MAX_NUMBER_OF_PROCESSES;
MAX_NUMBER_OF_PROCESSES = SYSTEM_LIMIT_NUMBER_OF_PROCESSES;

global MIN_PRIORITY_VALUE;
MIN_PRIORITY_VALUE = 1;

global MAX_PRIORITY_VALUE;
MAX_PRIORITY_VALUE = 239;

global MAX_LOCK_LEVEL;
MAX_LOCK_LEVEL = 16;

global NULL_PROCESS_ID;
NULL_PROCESS_ID = 0;

global PROCESS_STATE_TYPE
PROCESS_STATE_TYPE.DORMANT = 0;
PROCESS_STATE_TYPE.READY = 1;
PROCESS_STATE_TYPE.RUNNING = 2;
PROCESS_STATE_TYPE.WAITING = 3;
              
global OPERATING_MODE_TYPE;
OPERATING_MODE_TYPE.IDLE = 0;
OPERATING_MODE_TYPE.COLD_START = 1;
OPERATING_MODE_TYPE.WARM_START = 2;
OPERATING_MODE_TYPE.NORMAL = 3;

global DEADLINE_TYPE
DEADLINE_TYPE.SOFT = 0;
DEADLINE_TYPE.HARD = 1;

global START_CONDITION_TYPE
START_CONDITION_TYPE.NORMAL_START = 0;
START_CONDITION_TYPE.PARTITION_RESTART = 1;
START_CONDITION_TYPE.HM_MODULE_RESTART = 2;
START_CONDITION_TYPE.HM_PARTITION_RESTART = 3;

global MAX_NUMBER_OF_SAMPLING_PORTS;
MAX_NUMBER_OF_SAMPLING_PORTS = SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS;

global VALIDITY_TYPE;
VALIDITY_TYPE.INVALID = 0;
VALIDITY_TYPE.VALID = 1;

global MAX_NUMBER_OF_QUEUING_PORTS;
MAX_NUMBER_OF_QUEUING_PORTS = SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS;

global MAX_NUMBER_OF_BUFFERS;
MAX_NUMBER_OF_BUFFERS = SYSTEM_LIMIT_NUMBER_OF_BUFFERS;

global MAX_NUMBER_OF_BLACKBOARDS;
MAX_NUMBER_OF_BLACKBOARDS = SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS;

global EMPTY_INDICATOR_TYPE;
EMPTY_INDICATOR_TYPE.EMPTY = 0;
EMPTY_INDICATOR_TYPE.OCCUPIED = 1;

global MAX_NUMBER_OF_SEMAPHORES;
MAX_NUMBER_OF_SEMAPHORES = SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES;

global MAX_SEMAPHORE_VALUE;
MAX_SEMAPHORE_VALUE = 32767;

global MAX_NUMBER_OF_EVENTS;
MAX_NUMBER_OF_EVENTS = SYSTEM_LIMIT_NUMBER_OF_EVENTS;

global EVENT_STATE_TYPE;
EVENT_STATE_TYPE.DOWN = 0;
EVENT_STATE_TYPE.UP = 1;

global MAX_ERROR_MESSAGE_SIZE;
MAX_ERROR_MESSAGE_SIZE = 128;

global ERROR_CODE_TYPE;
ERROR_CODE_TYPE.DEADLINE_MISSED = 0;
ERROR_CODE_TYPE.APPLICATION_ERROR = 1;
ERROR_CODE_TYPE.NUMERIC_ERROR = 2;
ERROR_CODE_TYPE.ILLEGAL_REQEUST = 3;
ERROR_CODE_TYPE.STACK_OVERFLOW = 4;
ERROR_CODE_TYPE.MEMORY_VIOLATION = 5;
ERROR_CODE_TYPE.HARDWARE_FAULT = 6;
ERROR_CODE_TYPE.POWER_FAIL = 7;
