function [PARTITION_STATUS,RETURN_CODE] = GET_PARTITION_STATUS()

global RETURN_CODE_TYPE;
global Current_Partition_STATUS;

[PARTITION_STATUS] = Current_Partition_STATUS;
[RETURN_CODE] = RETURN_CODE_TYPE.NO_ERROR;
end