global PROCESS_STATUS
 PROCESS_STATUS.DEADLINE_TIME=1;
 PROCESS_STATUS.CURRENT_PRIORITY ;
 PROCESS_STATUS.PROCESS_STATUS;
 PROCESS_STATUS.ATTRIBUTES.NAME;
 PROCESS_STATUS.ATTRIBUTES.ENTRY_POINT ;
 PROCESS_STATUS.ATTRIBUTES.STACK_SIZE  ;
 PROCESS_STATUS.ATTRIBUTES.BASE_PRIORITY ;
 PROCESS_STATUS.ATTRIBUTES.PERIOD ;
 PROCESS_STATUS.ATTRIBUTES.TIME_CAPACITY ;
 PROCESS_STATUS.ATTRIBUTES.DEADLINE;