function [BUFFER_ID,RETURN_CODE]=CREATE_BUFFER(BUFFER_NAME,MAX_MESSAGE_SIZE,MAX_NB_MESSAGE,QUEUING_DISCIPLINE)
	
        global SYSTEM_LIMIT_NUMBER_OF_BUFFERS
        global SYSTEM_NUMBER_OF_BUFFERS
        global RETURN_CODE_TYPE
        global OPERATING_MODE_TYPE
        global CURRENT_PARTITION_STATUS
        global BUFFER_ATTRIBUTE
        global Waiting_Buffer_Set
        
  		if INVALID_NAME(BUFFER_NAME) == 1 
  			RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
			return
        end
        
        if INVALID_MAX_MESSAGE_SIZE(MAX_MESSAGE_SIZE) == 1
		 
			RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    		return;
        end
       
		if INVALID_MAX_NB_MESSAGE(MAX_NB_MESSAGE) == 0
		
			RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    		return;
        end
         
        
		if INVALID_QUEUING_DISCIPLINE(QUEUING_DISCIPLINE) == 0
		
			RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    		return;
        end
         
		if SYSTEM_NUMBER_OF_BUFFERS == SYSTEM_LIMIT_NUMBER_OF_BUFFERS
    		
    		RETURN_CODE = RETURN_CODE_TYPE.INVALID_CONFIG;
    		return;
        end
        
%   		if(@.<NAME:BLACKBOARD_NAME>:Blackboard_Set)
%     	{	
%     		*RETURN_CODE = NO_ACTION;
%     		return;
%     	}
 
      	if(CURRENT_PARTITION_STATUS.OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL)
        	
        	RETURN_CODE = RETURN_CODE_TYPE.INVALID_MODE;
        	return;
        end

%       	Buff.<NAME:NULL> : Buffer_Set;
		
        
        SYSTEM_NUMBER_OF_BUFFERS = SYSTEM_NUMBER_OF_BUFFERS + 1;
        BUFFER_ID  = SYSTEM_NUMBER_OF_BUFFERS
        
        BUF = BUFFER_TYPE(BUFFER_NAME,BUFFER_ID,BUFFER_ATTRIBUTE.NB_MESSAGE,BUFFER_ATTRIBUTE.MAX_NB_MESSAGE,BUFFER_ATTRIBUTE.MAX_MESSAGE_SIZE,BUFFER_ATTRIBUTE.WAITING_PROCESSES,BUFFER_ATTRIBUTE.QUEUING_DISCIPLINE);
         Waiting_Buffer_Set{BUFFER_ID,1} = BUF

        %        BUFFER_ATTRIBUTE.NAME = BUFFER_NAME;
       
      
% 		BUF.NAME = BUFFER_NAME;
% 		BUF.NB_MESSAGE = 0;
% 		BUF.MAX_NB_MESSAGE = MAX_NB_MESSAGE;
% 		BUF.MAX_MESSAGE_SIZE = MAX_MESSAGE_SIZE;
% 		BUF.WAITING_PROCESSES = 0;
% 		BUF.QUEUING_DISCIPLINE = QUEUING_DISCIPLINE; 		
  		
  		
  		
  		RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR
        
	
