global BUFFER_ATTRIBUTE

BUFFER_ATTRIBUTE.NB_MESSAGE=0;
BUFFER_ATTRIBUTE.MAX_NB_MESSAGE=4;
BUFFER_ATTRIBUTE.MAX_MESSAGE_SIZE=8;
BUFFER_ATTRIBUTE.WAITING_PROCESSES=0;
BUFFER_ATTRIBUTE.QUEUING_DISCIPLINE=0;



