global BLACKBOARD_TYPE
BLACKBOARD_TYPE.ID;
BLACKBOARD_TYPE.NAME;	
BLACKBOARD_TYPE.EMPTY_INDICATOR;
BLACKBOARD_TYPE.MAX_MESSAGE_SIZE;
BLACKBOARD_TYPE.WAITING_PROCESSES;
BLACKBOARD_TYPE.MESSAGE_ADDR;
BLACKBOARD_TYPE.LENGTH;
