global SPORT
SPORT.PORT_DIRECTION=1;
SPORT.EMPTY_INDICATOR=1;
SPORT.LENGTH =5;

global EMPTY_INDICATOR_TYPE
EMPTY_INDICATOR_TYPE.EMPTY = 0;
EMPTY_INDICATOR_TYPE.OCCUPIED = 1;

global PORT_DIRECTION_TYPE
PORT_DIRECTION_TYPE.SOURCE = 0;
PORT_DIRECTION_TYPE.DESTINATION = 1;