[QUEUING_PORT_ID,RETURN_CODE ] = CREATE_QUEUING_PORT('cy',100,100,0,0 )

[ RETURN_CODE ] = SEND_QUEUING_MESSAGE( 143,1,3,1)

¸ÄPORT_DIRECTION=1
[ LENGTH,RETURN_CODE ] =  RECEIVE_QUEUING_MESSAGE( 82,1,6 )

[ QUEUING_PORT_ID,RETURN_CODE ] = GET_QUEUING_PORT_ID( 'cy' )

[ QUEUING_PORT_STATUS,RETURN_CODE ] = GET_QUEUING_PORT_STATUS( 280 )

¸ÄPORT_DIRECTION=1
[RETURN_CODE ] = CLEAR_QUEUING_PORT(QUEUING_PORT_ID )