function [RETURN_CODE] = SET_PARTITION_MODE(OPERATING_MODE)

global RETURN_CODE_TYPE;
global OPERATING_MODE_TYPE;
global Current_Partition_STATUS;
global MAX_LOCK_LEVEL;

if INVAILD_OPERATING_MODE(OPERATING_MODE) == 1
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    return;
end

if OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL && Current_Partition_STATUS.OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL
    RETURN_CODE = RETURN_CODE_TYPE.NO_ACTION;
    return;
end

if OPERATING_MODE == OPERATING_MODE_TYPE.WARM_START && Current_Partition_STATUS.OPERATING_MODE == OPERATING_MODE_TYPE.COLD_START
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_MODE;
    return;
end

Current_Partition_STATUS.OPERATING_MODE = OPERATING_MODE;

if OPERATING_MODE == OPERATING_MODE_TYPE.IDLE
    SHUT_DOWN_PARTITION();
end

if OPERATING_MODE == OPERATING_MODE_TYPE.WARM_START || OPERATING_MODE == OPERATING_MODE_TYPE.COLD_START
    Current_Partition_STATUS.LOCK_LEVEL = round(MAX_LOCK_LEVEL *rand(1,1) );
end

if OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL
    Current_Partition_STATUS.LOCK_LEVEL = 0;
end

[RETURN_CODE] = RETURN_CODE_TYPE.NO_ERROR;

