function [ RETURN_CODE ] = CREATE_ERROR_HANDLER( ENTRY_POINT,STACK_SIZE )

global RETURN_CODE_TYPE;
global OPERATING_MODE_TYPE;
global Current_Partition_STATUS;
global maximum_number_of_error_hander;

if INVALID_ERROR_HANDER()
    RETURN_CODE=RETURN_CODE_TYPE.NO_ERROR;
    return;
end

if NUMBER_OF_ERROR_HANDER()>maximum_number_of_error_hander
    RETURN_CODE=RETURN_CODE_TYPE.INVALID_CONFIG;
    return;
end

if STACK_SIZE<0 || STACK_SIZE>31
    RETURN_CODE=RETURN_CODE_TYPE.INVALID_CONFIG;
    return;
end
    
if Current_Partition_STATUS.OPERATING_MODE == OPERATING_MODE_TYPE.NORMAL
     RETURN_CODE = RETURN_CODE_TYPE.INVALID_MODE;
     return;
end

ATTRIBUTE=struct('ID',0,'DEADLINE_TIME',10,'CURRENT_PRIORITY',31,'PROCESS_STATE',0,'PERIOD',10,'TIME_CAPACITY',5,'ENTRY_POINT',ENTRY_POINT,'STACK_SIZE',STACK_SIZE,'BASE_PRIORITY',31,'DEADLINE',30,'NAME',999);            
CREATE_PROCESS(ATTRIBUTE);
RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR;
return;

end

