function [ RETURN_CODE ] = REPORT_APPLICATION_MESSAGE( MESSAGE_ADDR,LENGTH )

global RETURN_CODE_TYPE;
global HealthMonitor_Set;

MAX_ERROR_MESSAGE_SIZE=128;

if LENGTH>MAX_ERROR_MESSAGE_SIZE
    RETURN_CODE=RETURN_CODE_TYPE.INVALID_PARAM;
    disp(RETURN_CODE);
    disp('a');
    return;
end

HEALTH = ERROR_STATUS_ATTRIBUTE_TYPE(-1,-1,-1,-1);    
HEALTH.MESSAGE = cell(1,MAX_ERROR_MESSAGE_SIZE);    
HealthMonitor_Set{1,1} = HEALTH;

TEMP_LENGTH = 1;
while(TEMP_LENGTH<LENGTH+1)
    HealthMonitor_Set{1,1}.MESSAGE{1,TEMP_LENGTH}=MESSAGE_ADDR+TEMP_LENGTH;
    TEMP_LENGTH = TEMP_LENGTH + 1;
end

HealthMonitor_Set{1,1}.LENGTH=LENGTH;
RETURN_CODE=RETURN_CODE_TYPE.NO_ERROR;
disp(RETURN_CODE);
disp('b');
return;

end

