function [ RETURN_CODE ] = REPORT_APPLICATION_MESSAGE( MESSAGE_ADDR,LENGTH )

global RETURN_CODE_TYPE;
global HealthMonitor_Set;
global MAX_ERROR_MESSAGE_SIZE

if LENGTH>MAX_ERROR_MESSAGE_SIZE
    RETURN_CODE=RETURN_CODE_TYPE.INVALID_PARAM;
    return;
end

num=numel(HealthMonitor_Set)+1;
HEALTH = ERROR_STATUS_ATTRIBUTE_TYPE(-1,-1,-1,-1);    
HEALTH.MESSAGE = cell(1,MAX_ERROR_MESSAGE_SIZE); 
HEALTH.LENGTH=LENGTH;
HealthMonitor_Set{1,num} = HEALTH;

TEMP_LENGTH = 1;
while(TEMP_LENGTH<LENGTH+1)
    HealthMonitor_Set{1,num}.MESSAGE{1,TEMP_LENGTH}=MESSAGE_ADDR+TEMP_LENGTH;
    TEMP_LENGTH = TEMP_LENGTH + 1;
end

RETURN_CODE=RETURN_CODE_TYPE.NO_ERROR;
return;

end

