global RETURN_CODE_TYPE

RETURN_CODE_TYPE.NO_ERROR = 0;   
RETURN_CODE_TYPE.NO_ACTION = 1;  
RETURN_CODE_TYPE.NOT_AVAILABLE = 2;   
RETURN_CODE_TYPE.INVALID_PARAM = 3;  
RETURN_CODE_TYPE.INVALID_CONFIG = 4;  
RETURN_CODE_TYPE.INVALID_MODE = 5;  
RETURN_CODE_TYPE.TIMED_OUT = 6;       

global PROCESS_STATE_TYPE
PROCESS_STATE_TYPE.DORMANT = 0;
PROCESS_STATE_TYPE.READY = 1;
PROCESS_STATE_TYPE.RUNNING = 2;
PROCESS_STATE_TYPE.WAITING = 3;
              

global ATTRIBUTES %这些数值是自己定义的，可以随意修改
ATTRIBUTES.PERIOD=1;
ATTRIBUTES.TIME_CAPACITY=2;
ATTRIBUTES.ENTRY_POINT=1;
ATTRIBUTES.STACK_SIZE=2;
ATTRIBUTES.BASE_PRIORITY=1;
ATTRIBUTES.DEADLINE_TYPE.DEADLINE=1;
ATTRIBUTES.NAME='pkb';





global OPERATING_MODE_TYPE
OPERATING_MODE_TYPE.IDLE = 0;
OPERATING_MODE_TYPE.COLD_START = 1;
OPERATING_MODE_TYPE.WARM_START = 2;
OPERATING_MODE_TYPE.NORMAL = 3;

global ID;
global DEADLINE_TYPE
DEADLINE_TYPE.SOFT = 0;
DEADLINE_TYPE.HARD = 1;

global Current_Partition_STATUE
Current_Partition_STATUE.OPERATING_MODE=1;
Current_Partition_STATUE.LOCK_LEVEL=0;

global Process_Set
Process_Set = cell(1,255);
 
global Process_Waiting_Resource_Set
Process_Waiting_Resource_Set= cell(1,255);
global Ready_Processes_set
Ready_Processes_set=cell(1,255);
global Dormant_Processes_set
Dormant_Processes_set=cell(1,255);
global Running_Processes_set;
Running_Processes_set=cell(1,255);
global Waiting_Processes_set
Waiting_Processes_set=cell(1,255);

% global Buffer
% Buffer = cell(1,255);

global Current_Partition_Timer;
Current_Partition_Timer=cell(1,255);

global ERROR_HANDLER_PROCESS_ID;
ERROR_HANDLER_PROCESS_ID=0;
global INFINITE_TIME_VALUE;
INFINITE_TIME_VALUE=-1;

global Current_Process
Current_Process.ID=6;
Current_Process.DEADLINE_TIME=10;
Current_Process.CURRENT_PRIORITY =3;
Current_Process.PROCESS_STATE =0;
Current_Process.PERIOD =0;
Current_Process.TIME_CAPACITY =5;
Current_Process.ENTRY_POIN =20;
Current_Process.STACK_SIZE =200;
Current_Process.BASE_PRIORITY =0;
Current_Process.DEADLINE=30;
Current_Process.NAME =4;

global Previous_Process
Previous_Process.ID=5;
Previous_Process.DEADLINE_TIME=10;
Previous_Process.CURRENT_PRIORITY=3;
Previous_Process.PROCESS_STATE=1;
Previous_Process.PERIOD=-1;
Previous_Process.TIME_CAPACITY=5;
Previous_Process.ENTRY_POIN=20;
Previous_Process.STACK_SIZE=200;
Previous_Process.BASE_PRIORITY=0;
Previous_Process.DEADLINE=30;
Previous_Process.NAME=3;


global Idel_Process
Idel_Process.ID=-1;
Idel_Process.PERIOD=1;
Idel_Process.TIME_CAPACITY=2;
Idel_Process.ENTRY_POINT=1;
Idel_Process.STACK_SIZE=2;
Idel_Process.BASE_PRIORITY=1;
Idel_Process.DEADLINE_TYPE.DEADLINE=1;
Idel_Process.NAME='idel';
Idel_Process.LOCK_LEVEL = 0;
Idel_Process.OPERATING_MODE = 0;

global LOCK_LEVEL
LOCK_LEVEL = 0;
global MAX_LOCK_LEVEL
MAX_LOCK_LEVEL = 0;

global Waiting_Buffer_Set 
  Waiting_Buffer_Set = cell(8,255);
  
global SYSTEM_NUMBER_OF_BUFFERS
SYSTEM_NUMBER_OF_BUFFERS = 0;

global MAX_NUMBER_OF_SAMPLING_PORTS
MAX_NUMBER_OF_SAMPLING_PORTS = 255;

global SYSTEM_NUMBER_OF_SAMPLING_PORTS
SYSTEM_NUMBER_OF_SAMPLING_PORTS = 0;
global Sampling_Set
Sampling_Set = cell(1,255);
global Sampling_obj
Sampling_obj ={};
% global SAMPLING_PORT_STATUS
% SAMPLING_PORT_STATUS.REFRESH_PERIOD;
% SAMPLING_PORT_STATUS.MAX_MESSAGE_SIZE; 
% SAMPLING_PORT_STATUS.PORT_DIRECTION;
% SAMPLING_PORT_STATUS.LAST_MSG_VALIDITY; 

global MAX_NUMBER_OF_PROCESS
MAX_NUMBER_OF_PROCESS = 255;

global SPORT
SPORT.PORT_DIRECTION=1;
SPORT.EMPTY_INDICATOR=1;
SPORT.LENGTH =5;

global EMPTY_INDICATOR_TYPE
EMPTY_INDICATOR_TYPE.EMPTY = 0;
EMPTY_INDICATOR_TYPE.OCCUPIED = 1;

global PORT_DIRECTION_TYPE
PORT_DIRECTION_TYPE.SOURCE = 0;
PORT_DIRECTION_TYPE.DESTINATION = 1;

global  VALIDITY_TYPE
 VALIDITY_TYPE.INVALID =0;
 VALIDITY_TYPE.VALID =1;
 global DATA_ZONE
 DATA_ZONE = cell(0);
 global SAMPING_PORT
 SAMPING_PORT = cell(MAX_NUMBER_OF_PROCESS);
 

