function [ RETURN_CODE,BLACKBOARD_STATUS  ] =  GET_BLACKBOARD_STATUS( BLACKBOARD_ID )
%UNTITLED8 此处显示有关此函数的摘要
%   此处显示详细说明
global RETURN_CODE_TYPE;
global Blackboard_Set;

if INVALID_ID(BLACKBOARD_ID)
    RETURN_CODE =  RETURN_CODE_TYPE.INVALID_PARAM;
    BLACKBOARD_STATUS=[];
			return;
end

    if FIND_BLACKBOARD_BYID( BLACKBOARD_ID )==0
         RETURN_CODE =  RETURN_CODE_TYPE.INVALID_PARAM;
         BLACKBOARD_STATUS=[];
			return;
    end 
    
BLACKBOARD_STATUS.EMPTY_INDICATOR=Blackboard_Set{1,FIND_BLACKBOARD_BYID( BLACKBOARD_ID )}.EMPTY_INDICATOR;
BLACKBOARD_STATUS.MAX_MESSAGE_SIZE = Blackboard_Set{1,FIND_BLACKBOARD_BYID( BLACKBOARD_ID )}.MAX_MESSAGE_SIZE;
BLACKBOARD_STATUS.WAITING_PROCESSES =  Blackboard_Set{1,FIND_BLACKBOARD_BYID( BLACKBOARD_ID )}.WAITING_PROCESSES;
RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR;




end

