function [ SEMAPHORE_STATUS,RETURN_CODE  ] = GET_SEMAPHORE_STATUS( SEMAPHORE_ID )

global RETURN_CODE_TYPE;
global Semaphore_Set;
global Semaphore_ID_Set;

if SEMAPHORE_INVALID_ID(SEMAPHORE_ID) == 0
    SEMAPHORE_STATUS.CURRENT_VALUE =-1;
    SEMAPHORE_STATUS.MAXIMUM_VALUE =-1;
    SEMAPHORE_STATUS.WAITING_PROCESSES =-1;
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    return;
end

ID=0;
for i=1:numel(Semaphore_ID_Set)
    if Semaphore_ID_Set(i)==SEMAPHORE_ID
        ID=i;
        break;
    end
end

SEMAPHORE_STATUS.CURRENT_VALUE =Semaphore_Set{1,ID}.CURRENT_VALUE;
SEMAPHORE_STATUS.MAXIMUM_VALUE =Semaphore_Set{1,ID}.MAXIMUM_VALUE;
SEMAPHORE_STATUS.WAITING_PROCESSES =Semaphore_Set{1,ID}.WAITING_PROCESSES;
RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR;

end

