function INSERT_INTO_SEMAPHORE_QUEUE(SEMAPHORE_ID,PROCESS_ID)

global Semaphore_Set;

LOCATION = FIND_SEMAPHORE_INDEX( SEMAPHORE_ID );

SEMAPHORE_QUEUE_ID = numel(Semaphore_Set{1,LOCATION}.SEMAPHORE_QUEUE) + 1;
Semaphore_Set{1,LOCATION}.SEMAPHORE_QUEUE(SEMAPHORE_QUEUE_ID) = PROCESS_ID;

end

