function INSERT_INTO_SEMAPHORE_QUEUE(SEMAPHORE_ID,PROCESS_ID)

global Semaphore_Set;

SEMAPHORE_QUEUE_ID = numel(Semaphore_Set{1,SEMAPHORE_ID}.SEMAPHORE_QUEUE) + 1;
Semaphore_Set{1,SEMAPHORE_ID}.SEMAPHORE_QUEUE(SEMAPHORE_QUEUE_ID) = PROCESS_ID;

end

