global ERROR_HANDLER_PROCESS_ID
ERROR_HANDLER_PROCESS_ID = 0;

global MAX_NAME_LENGTH 
MAX_NAME_LENGTH = 30; 
global INFINITE_TIME_VALUE
INFINITE_TIME_VALUE = -1;
global MIN_PRIORITY_VALUE
MIN_PRIORITY_VALUE = 1;
global MAX_PRIORITY_VALUE
MAX_PRIORITY_VALUE = 239;
global MAX_LOCK_LEVEL
MAX_LOCK_LEVEL = 16;
global NULL_PROCESS_ID
NULL_PROCESS_ID = 0
global MAX_ERROR_MESSAGE_SIZE
MAX_ERROR_MESSAGE_SIZE = 128;
global MAX_SEMAPHORE_VALUE
MAX_SEMAPHORE_VALUE = 32767;

