global SYSTEM_LIMIT_NUMBER_OF_PARTITIONS;
SYSTEM_LIMIT_NUMBER_OF_PARTITIONS = 32;

global SYSTEM_LIMIT_NUMBER_OF_MESSAGES;
SYSTEM_LIMIT_NUMBER_OF_MESSAGES = 512;

global SYSTEM_LIMIT_MESSAGE_SIZE;
SYSTEM_LIMIT_MESSAGE_SIZE = 8192;

global SYSTEM_LIMIT_NUMBER_OF_PROCESSSE;
SYSTEM_LIMIT_NUMBER_OF_PROCESSSE = 128;

global SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS;
SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS = 512;

global SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS;
SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS = 512;

global SYSTEM_LIMIT_NUMBER_OF_BUFFERS;
SYSTEM_LIMIT_NUMBER_OF_BUFFERS = 256;

global SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS;
SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS = 256;

global SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES;
SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES = 256;

global SYSTEM_LIMIT_NUMBER_OF_EVENTS;
SYSTEM_LIMIT_NUMBER_OF_EVENTS = 256;

global MAX_NAME_LENGTH;
MAX_NAME_LENGTH = 30;

global RETURN_CODE_TYPE
RETURN_CODE_TYPE.NO_ERROR = 0;   
RETURN_CODE_TYPE.NO_ACTION = 1;  
RETURN_CODE_TYPE.NOT_AVAILABLE = 2;   
RETURN_CODE_TYPE.INVALID_PARAM = 3;  
RETURN_CODE_TYPE.INVALID_CONFIG = 4;  
RETURN_CODE_TYPE.INVALID_MODE = 5;  
RETURN_CODE_TYPE.TIMED_OUT = 6;       

global PORT_DIRECTION_TYPE;
PORT_DIRECTION_TYPE.SOURCE = 0;
PORT_DIRECTION_TYPE.DESTINATION = 1;

global QUEUING_DISCIPLINE_TYPE;
QUEUING_DISCIPLINE_TYPE.FIFO = 0;
QUEUING_DISCIPLINE_TYPE.PRIORITY = 1;

global INFINITE_TIME_VALUE;
INFINITE_TIME_VALUE = -1;

global MAX_NUMBER_OF_PROCESSSE;
MAX_NUMBER_OF_PROCESSSE = SYSTEM_LIMIT_NUMBER_OF_PROCESSSE;

global MIN_PRIORITY_VALUE;
MIN_PRIORITY_VALUE = 1;

global MAX_PRIORITY_VALUE;
MAX_PRIORITY_VALUE = 239;

global MAX_LOCK_LEVEL;
MAX_LOCK_LEVEL = 16;

global NULL_PROCESS_ID;
NULL_PROCESS_ID = 0;

global PROCESS_STATE_TYPE
PROCESS_STATE_TYPE.DORMANT = 0;
PROCESS_STATE_TYPE.READY = 1;
PROCESS_STATE_TYPE.RUNNING = 2;
PROCESS_STATE_TYPE.WAITING = 3;
              
global OPERATING_MODE_TYPE
OPERATING_MODE_TYPE.IDLE = 0;
OPERATING_MODE_TYPE.COLD_START = 1;
OPERATING_MODE_TYPE.WARM_START = 2;
OPERATING_MODE_TYPE.NORMAL = 3;

global DEADLINE_TYPE
DEADLINE_TYPE.SOFT = 0;
DEADLINE_TYPE.HARD = 1;

global START_CONDITION_TYPE
START_CONDITION_TYPE.NORMAL_START = 0;
START_CONDITION_TYPE.PARTITION_RESTART = 1;
START_CONDITION_TYPE.HM_MODULE_RESTART = 2;
START_CONDITION_TYPE.HM_PARTITION_RESTART = 3;

global MAX_NUMBER_OF_SAMPLING_PORTS;
MAX_NUMBER_OF_SAMPLING_PORTS = SYSTEM_LIMIT_NUMBER_OF_SAMPLING_PORTS;

global VALIDITY_TYPE;
VALIDITY_TYPE.INVALID = 0;
VALIDITY_TYPE.VALID = 1;

global MAX_NUMBER_OF_QUEUING_PORTS;
MAX_NUMBER_OF_QUEUING_PORTS = SYSTEM_LIMIT_NUMBER_OF_QUEUING_PORTS;

global MAX_NUMBER_OF_BUFFERS;
MAX_NUMBER_OF_BUFFERS = SYSTEM_LIMIT_NUMBER_OF_BUFFERS;

global MAX_NUMBER_OF_BLACKBOARDS;
MAX_NUMBER_OF_BLACKBOARDS = SYSTEM_LIMIT_NUMBER_OF_BLACKBOARDS;

global EMPTY_INDICATOR_TYPE;
EMPTY_INDICATOR_TYPE.EMPTY = 0;
EMPTY_INDICATOR_TYPE.OCCUPIED = 1;

global MAX_NUMBER_OF_SEMAPHORES;
MAX_NUMBER_OF_SEMAPHORES = SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES;

global MAX_SEMAPHORE_VALUE;
MAX_SEMAPHORE_VALUE = 32767;

global MAX_NUMBER_OF_EVENTS;
MAX_NUMBER_OF_EVENTS = SYSTEM_LIMIT_NUMBER_OF_EVENTS;

global EVENT_STATE_TYPE;
EVENT_STATE_TYPE.DOWN = 0;
EVENT_STATE_TYPE.UP = 1;

global MAX_ERROR_MESSAGE_SIZE;
MAX_ERROR_MESSAGE_SIZE = 128;

global ERROR_CODE_TYPE;
ERROR_CODE_TYPE.DEADLINE_MISSED = 0;
ERROR_CODE_TYPE.APPLICATION_ERROR = 1;
ERROR_CODE_TYPE.NUMERIC_ERROR = 2;
ERROR_CODE_TYPE.ILLEGAL_REQEUST = 3;
ERROR_CODE_TYPE.STACK_OVERFLOW = 4;
ERROR_CODE_TYPE.MEMORY_VIOLATION = 5;
ERROR_CODE_TYPE.HARDWARE_FAULT = 6;
ERROR_CODE_TYPE.POWER_FAIL = 7;

%buffer

global PROCESS_ATTRIBUTE_TYPE %这些数值是自己定义的，可以随意修改
PROCESS_ATTRIBUTE_TYPE.PERIOD=1;
PROCESS_ATTRIBUTE_TYPE.TIME_CAPACITY=2;
PROCESS_ATTRIBUTE_TYPE.ENTRY_POINT=1;
PROCESS_ATTRIBUTE_TYPE.STACK_SIZE=2;
PROCESS_ATTRIBUTE_TYPE.BASE_PRIORITY=1;
PROCESS_ATTRIBUTE_TYPE.DEADLINE_TYPE.DEADLINE=1;
PROCESS_ATTRIBUTE_TYPE.NAME='pkb';







global ID

global CURRENT_PARTITION_STATUS
CURRENT_PARTITION_STATUS.OPERATING_MODE=0;
CURRENT_PARTITION_STATUS.LOCK_LEVEL=0;

global Process_Set
Process_Set = cell(0);
 
global Process_Waiting_Resource_Set
Process_Waiting_Resource_Set= [];
global Ready_Processes_set
Ready_Processes_set=[];
global Dormant_Processes_set
Dormant_Processes_set=[];
global Running_Processes_set;
Running_Processes_set=[];
global Waiting_Processes_set
Waiting_Processes_set=[];


%  global BUFFER_ATTRIBUTE;
 global Buffer_set
Buffer_set = cell(0);
global Waiting_Buffer_Set
Waiting_Buffer_Set = [];
global Buffer_name_set;
Buffer_name_set = cell(0);
global Buffer_id_set;
Buffer_id_set = [];

global SYSTEM_NUMBER_OF_BUFFERS
SYSTEM_NUMBER_OF_BUFFERS = 0;

global Current_Partition_Timer;
Current_Partition_Timer=cell(1,255);

global ERROR_HANDLER_PROCESS_ID;
ERROR_HANDLER_PROCESS_ID=0;

global Time_Out_Signal
Time_Out_Signal = 1;
global Current_Process
Current_Process.ID=6;
Current_Process.DEADLINE_TIME=10;
Current_Process.CURRENT_PRIORITY =3;
Current_Process.PROCESS_STATE =0;
Current_Process.PERIOD =0;
Current_Process.TIME_CAPACITY =5;
Current_Process.ENTRY_POIN =20;
Current_Process.STACK_SIZE =200;
Current_Process.BASE_PRIORITY =0;
Current_Process.DEADLINE=30;
Current_Process.NAME =4;

global Previous_Process
Previous_Process.ID=5;
Previous_Process.DEADLINE_TIME=10;
Previous_Process.CURRENT_PRIORITY=3;
Previous_Process.PROCESS_STATE=1;
Previous_Process.PERIOD=-1;
Previous_Process.TIME_CAPACITY=5;
Previous_Process.ENTRY_POIN=20;
Previous_Process.STACK_SIZE=200;
Previous_Process.BASE_PRIORITY=0;
Previous_Process.DEADLINE=30;
Previous_Process.NAME=3;

global Current_Partition_STATUS
Current_Partition_STATUS.OPERATING_MODE=OPERATING_MODE_TYPE.COLD_START ;
Current_Partition_STATUS.LOCK_LEVEL=0;

global SYSTEM_TIME_TYPE
SYSTEM_TIME_TYPE = 2^64;


global MAX_NUMBER_OF_PROCESS
MAX_NUMBER_OF_PROCESS = 255;

global PROCESS_NAME_SET
 PROCESS_NAME_SET = cell(0);
 global PROCESS_ID_SET
 PROCESS_ID_SET = [];

 global   BUFFER_STATUS
   BUFFER_STATUS.NB_MESSAGE=0;        
   BUFFER_STATUS.MAX_NB_MESSAGE=0;   
   BUFFER_STATUS.MAX_MESSAGE_SIZE=0;    
   BUFFER_STATUS.WAITING_PROCESSES=0;
   
 global DATA_ZONE
 DATA_ZONE = cell(0);
 
 global BUFFER
 BUFFER = cell(MAX_NUMBER_OF_PROCESS);
 global TIMER_TYPE
 TIMER_TYPE.TRUE=0;
 %port
 
 
              
global ATTRIBUTES %这些数值是自己定义的，可以随意修改
ATTRIBUTES.PERIOD=1;
ATTRIBUTES.TIME_CAPACITY=2;
ATTRIBUTES.ENTRY_POINT=1;
ATTRIBUTES.STACK_SIZE=2;
ATTRIBUTES.BASE_PRIORITY=1;
ATTRIBUTES.DEADLINE_TYPE.DEADLINE=1;
ATTRIBUTES.NAME='pkb';









global Current_Partition_STATUE
Current_Partition_STATUE.OPERATING_MODE=1;
Current_Partition_STATUE.LOCK_LEVEL=0;



% global Buffer
% Buffer = cell(1,255);








global Idel_Process
Idel_Process.ID=-1;
Idel_Process.PERIOD=1;
Idel_Process.TIME_CAPACITY=2;
Idel_Process.ENTRY_POINT=1;
Idel_Process.STACK_SIZE=2;
Idel_Process.BASE_PRIORITY=1;
Idel_Process.DEADLINE_TYPE.DEADLINE=1;
Idel_Process.NAME='idel';
Idel_Process.LOCK_LEVEL = 0;
Idel_Process.OPERATING_MODE = 0;

global LOCK_LEVEL
LOCK_LEVEL = 0;

  


global SYSTEM_NUMBER_OF_SAMPLING_PORTS
SYSTEM_NUMBER_OF_SAMPLING_PORTS = 0;
global Sampling_Set
Sampling_Set = cell(1,255);
global Sampling_obj
Sampling_obj ={};
% global SAMPLING_PORT_STATUS
% SAMPLING_PORT_STATUS.REFRESH_PERIOD;
% SAMPLING_PORT_STATUS.MAX_MESSAGE_SIZE; 
% SAMPLING_PORT_STATUS.PORT_DIRECTION;
% SAMPLING_PORT_STATUS.LAST_MSG_VALIDITY; 



global SPORT
SPORT.PORT_DIRECTION=1;
SPORT.EMPTY_INDICATOR=1;
SPORT.LENGTH =5;






 global SAMPING_PORT
 SAMPING_PORT = cell(MAX_NUMBER_OF_PROCESS);
 


