function INSERT_INTO_QUEUE_PORT(QUEUING_PORT_ID,PROCESS_ID)

global 	Queuing_Set;

LOCATION = FIND_QUEUING_PORT_INDEX( QUEUING_PORT_ID );

QUEUE_ID = numel(Queuing_Set{1,LOCATION}.QUEUE) + 1;
Queuing_Set{1,LOCATION}.QUEUE(QUEUE_ID) = PROCESS_ID;

end

