function [ ERROR_STATUS,RETURN_CODE ] = GET_ERROR_STATUS()

global RETURN_CODE_TYPE;
global Error_Process;
global PRO;

flag=IF_HANDLER_PROCESS(PRO.ID);
if flag==0
    RETURN_CODE=RETURN_CODE_TYPE.INVALID_CONFIG;
    ERROR_STATUS.ERROR_CODE = -1; 
    ERROR_STATUS.LENGTH = -1;
    ERROR_STATUS.FAILED_PROCESS_ID = -1;
    ERROR_STATUS.FAILED_ADDRESS = -1;
    disp(RETURN_CODE);
    disp('a');
    return;
end

num=NUMBER_OF_ERROR_PROCESS();
if num==0
    RETURN_CODE=RETURN_CODE_TYPE.NO_ACTION;
    ERROR_STATUS.ERROR_CODE = -1; 
    ERROR_STATUS.LENGTH = -1;
    ERROR_STATUS.FAILED_PROCESS_ID = -1;
    ERROR_STATUS.FAILED_ADDRESS = -1;
    disp(RETURN_CODE);
    disp('b');
    return;
end

ERROR_STATUS.ERROR_CODE = Error_Process{1,1}.ERROR_CODE; 
ERROR_STATUS.LENGTH = Error_Process{1,1}.ERROR_CODE;
ERROR_STATUS.FAILED_PROCESS_ID = Error_Process{1,1}.ERROR_CODE;
ERROR_STATUS.FAILED_ADDRESS = Error_Process{1,1}.ERROR_CODE;
Error_Process{1,1}=[];

RETURN_CODE=RETURN_CODE_TYPE.NO_ACTION;
disp(RETURN_CODE);
disp('c');
return;

end

