function [ SEMAPHORE_STATUS,RETURN_CODE  ] = GET_SEMAPHORE_STATUS( SEMAPHORE_ID )

global RETURN_CODE_TYPE;
global Semaphore_Set;
global Semaphore_ID_Set;


flag=INVALID_ID(SEMAPHORE_ID);
if flag == 0
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM;
    disp(RETURN_CODE);
    disp('a');
    return;
end

ID=0;
for i=1:255
    if Semaphore_ID_Set{1,i}==SEMAPHORE_ID
        ID=i;
        break;
    end
end

SEMAPHORE_STATUS.CURRENT_VALUE =Semaphore_Set{1,ID}.CURRENT_VALUE;
SEMAPHORE_STATUS.MAXIMUM_VALUE =Semaphore_Set{1,ID}.MAXIMUM_VALUE;
SEMAPHORE_STATUS.WAITING_PROCESSES =Semaphore_Set{1,ID}.WAITING_PROCESSES;
RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR;

disp(SEMAPHORE_STATUS.CURRENT_VALUE);
disp(SEMAPHORE_STATUS.MAXIMUM_VALUE);
disp(SEMAPHORE_STATUS.WAITING_PROCESSES);
disp(RETURN_CODE);
disp('b');

end

