global RETURN_CODE_TYPE

RETURN_CODE_TYPE.NO_ERROR = 0;   
RETURN_CODE_TYPE.NO_ACTION = 1;  
RETURN_CODE_TYPE.NOT_AVAILABLE = 2;   
RETURN_CODE_TYPE.INVALID_PARAM = 3;  
RETURN_CODE_TYPE.INVALID_CONFIG = 4;  
RETURN_CODE_TYPE.INVALID_MODE = 5;  
RETURN_CODE_TYPE.TIMED_OUT = 6;  

global PROCESS_STATE_TYPE
PROCESS_STATE_TYPE.DORMANT = 0;
PROCESS_STATE_TYPE.READY = 1;
PROCESS_STATE_TYPE.RUNNING = 2;
PROCESS_STATE_TYPE.WAITING = 3;

global Current_Partition_STATUS
Current_Partition_STATUS.LOCK_LEVEL=0;
Current_Partition_STATUS.OPERATING_MODE = PROCESS_STATE_TYPE.RUNNING ;


global Current_Process
Current_Process.ID = 1
Current_Process.STATUS.PROCESS_STATE=PROCESS_STATE_TYPE.WAITING
Current_Process.STATUS.ATTRIBUTES.PERIOD = -1 
global ERROR_HANDLER_PROCESS_ID 
ERROR_HANDLER_PROCESS_ID = -1;
global INFINITE_TIME_VALUE
INFINITE_TIME_VALUE = -1;

global MAX_PREOCESS_DELAY_TIME 
MAX_PREOCESS_DELAY_TIME = 255;

global Running_Processes_set;
Running_Processes_set=cell(1,255);
global Waiting_Processes_set
Waiting_Processes_set=cell(1,255);
global MAX_BUDGET_TIME
MAX_BUDGET_TIME = 255

